/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceGrafica;

import bancoDeDados.BancoDeDados;
import funcionarios.Cargo;
import funcionarios.Cozinheiro;
import funcionarios.Degustador;
import funcionarios.Funcionario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junio
 */
public class TelaFuncionario extends javax.swing.JFrame {

    ArrayList<JButton> botoes;
    ArrayList<JLabel> labels;
    ArrayList<JPanel> panels;
    String usuario = "postgres";
    String senha = "1Z2ht6b.";
    String nomedb = "CMP1611_Felipe_Valteci_Willian";
    
    public TelaFuncionario() {
        botoes = new ArrayList<>();
        labels = new ArrayList<>();
        panels = new ArrayList<>();
        
        initComponents();
        
        configurarTela();
        configurarCores();
    }
    
    public void mostrarFuncionarios(ArrayList<Funcionario> funcionarios) {
        
        DefaultTableModel model = (DefaultTableModel) 
                                   jTable_consulta.getModel();
        
        while (model.getRowCount()> 0)
            model.removeRow(0);
        
        for (Funcionario funcionario : funcionarios) {
            
            if (funcionario instanceof Cozinheiro cozinheiro) {
                
                model.addRow(new Object[]{
                    cozinheiro.getCpf(),
                    cozinheiro.getNome(),
                    cozinheiro.getDataIngresso(),
                    cozinheiro.getSalario(),
                    cozinheiro.getNomeFantasia(),
                    "Cozinheiro"
                });
                
            } else if (funcionario instanceof Degustador){
                model.addRow(new Object[]{
                    funcionario.getCpf(),
                    funcionario.getNome(),
                    funcionario.getDataIngresso(),
                    funcionario.getSalario(),
                    "",
                    "Degustador"
                });
                
            } else {
                model.addRow(new Object[]{
                    funcionario.getCpf(),
                    funcionario.getNome(),
                    funcionario.getDataIngresso(),
                    funcionario.getSalario(),
                    "",
                    "Editor"
                });
            }
        }
    }
    
    private void configurarCores() {
        jPanelFundo.setBackground(PaletaCores.FUNDO);
        jPanelTitulo.setBackground(PaletaCores.FUNDO);
        jTable_consulta.setBackground(PaletaCores.FUNDO);
        
        for (var label : labels)
            label.setForeground(PaletaCores.TEXTO_FONTE);
        
        for (var panel : panels)
            panel.setBackground(PaletaCores.PANEL_FUNDO);
        
        for (var botao : botoes)
            botao.setBackground(PaletaCores.BOTAO);
    }
    
    private void configurarTela() {
        this.setLocationRelativeTo(null);                                
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        txt_novoCPF.setVisible(false);
        txt_novoNome.setVisible(false);
        txt_novoSalario.setVisible(false);
        txt_novaDataIngresso.setVisible(false);
        txt_novoNomeFantasia.setVisible(false);
        
        lb_novoCPF.setVisible(false);
        lb_novoNome.setVisible(false);
        lb_novoSalario.setVisible(false);
        lb_novaDataIngresso.setVisible(false);
        lb_novoNomeFantasia.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dataIngresso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nomeFantasia = new javax.swing.JTextField();
        lb_nomeFantasia = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_salario = new javax.swing.JTextField();
        bt_cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_consulta = new javax.swing.JTable();
        bt_listarTodos = new javax.swing.JButton();
        bt_procurarCPF = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_cpfFuncionarioAserAtualizado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ckb_atualizarNomeFantasia = new javax.swing.JCheckBox();
        ckb_atualizarCPF = new javax.swing.JCheckBox();
        ckb_atualizarNome = new javax.swing.JCheckBox();
        ckb_atualizarDataIngresso = new javax.swing.JCheckBox();
        ckb_atualizarSalario = new javax.swing.JCheckBox();
        bt_atualizar = new javax.swing.JButton();
        lb_novoCPF = new javax.swing.JLabel();
        txt_novoCPF = new javax.swing.JTextField();
        txt_novoNome = new javax.swing.JTextField();
        lb_novoNome = new javax.swing.JLabel();
        lb_novaDataIngresso = new javax.swing.JLabel();
        txt_novaDataIngresso = new javax.swing.JTextField();
        lb_novoSalario = new javax.swing.JLabel();
        txt_novoSalario = new javax.swing.JTextField();
        lb_novoNomeFantasia = new javax.swing.JLabel();
        txt_novoNomeFantasia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_deleteCPF = new javax.swing.JTextField();
        bt_deletar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE GESTÃO DE FUNCIONÁRIOS");
        jPanelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 740, 40));
        labels.add(jLabel1);

        jPanelFundo.add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tipo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));
        labels.add(jLabel3);

        cb_tipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cozinheiro", "Degustador", "Editor" }));
        cb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 240, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        labels.add(jLabel4);
        jPanel2.add(txt_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 240, -1));
        jPanel2.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 240, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nome:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        labels.add(jLabel5);

        jLabel6.setText("(dd/mm/yyyy)");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));
        jPanel2.add(txt_dataIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Data de Ingresso:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        labels.add(jLabel7);
        jPanel2.add(txt_nomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, -1));

        lb_nomeFantasia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nomeFantasia.setText("Nome Fantasia:");
        jPanel2.add(lb_nomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        labels.add(lb_nomeFantasia);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Salário:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        labels.add(jLabel6);
        jPanel2.add(txt_salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 230, -1));

        bt_cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mouseReleased(evt);
            }
        });
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 360, 30));
        botoes.add(bt_cadastrar);

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 420, 370));
        panels.add(jPanel2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar Funcionários");
        jPanelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 160, 20));
        labels.add(jLabel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Data Ingresso", "Salário", "Nome Fantasia", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_consulta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 730, 250));

        bt_listarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_listarTodos.setText("Listar Todos");
        bt_listarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mouseReleased(evt);
            }
        });
        bt_listarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarTodosActionPerformed(evt);
            }
        });
        jPanel1.add(bt_listarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));
        botoes.add(bt_listarTodos);

        bt_procurarCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_procurarCPF.setText("Procurar por CPF");
        bt_procurarCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mouseReleased(evt);
            }
        });
        bt_procurarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_procurarCPFActionPerformed(evt);
            }
        });
        jPanel1.add(bt_procurarCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, 30));
        botoes.add(bt_procurarCPF);

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 760, 370));
        panels.add(jPanel1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Consultar Funcionários");
        jPanelFundo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));
        labels.add(jLabel8);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txt_cpfFuncionarioAserAtualizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 220, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("CPF do Funcionário a ser Atualizado:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        labels.add(jLabel13);

        ckb_atualizarNomeFantasia.setText("Atulizar Nome Fantasia");
        ckb_atualizarNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_atualizarNomeFantasiaActionPerformed(evt);
            }
        });
        jPanel3.add(ckb_atualizarNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        ckb_atualizarCPF.setText("Atulizar CPF");
        ckb_atualizarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_atualizarCPFActionPerformed(evt);
            }
        });
        jPanel3.add(ckb_atualizarCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        ckb_atualizarNome.setText("Atulizar Nome");
        ckb_atualizarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_atualizarNomeActionPerformed(evt);
            }
        });
        jPanel3.add(ckb_atualizarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        ckb_atualizarDataIngresso.setText("Atualizar Data Ingresso");
        ckb_atualizarDataIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_atualizarDataIngressoActionPerformed(evt);
            }
        });
        jPanel3.add(ckb_atualizarDataIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        ckb_atualizarSalario.setText("Atulizar Salário");
        ckb_atualizarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_atualizarSalarioActionPerformed(evt);
            }
        });
        jPanel3.add(ckb_atualizarSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        bt_atualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_atualizar.setText("Atualizar");
        bt_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mouseReleased(evt);
            }
        });
        jPanel3.add(bt_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 400, 30));
        botoes.add(bt_atualizar);

        lb_novoCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_novoCPF.setText("Novo CPF:");
        jPanel3.add(lb_novoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        labels.add(lb_novoCPF);
        jPanel3.add(txt_novoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, -1));
        jPanel3.add(txt_novoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, -1));

        lb_novoNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_novoNome.setText("Novo Nome:");
        jPanel3.add(lb_novoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        labels.add(lb_novoNome);

        lb_novaDataIngresso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_novaDataIngresso.setText("Nova Data Ingresso:");
        jPanel3.add(lb_novaDataIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));
        labels.add(lb_novaDataIngresso);
        jPanel3.add(txt_novaDataIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 110, -1));

        lb_novoSalario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_novoSalario.setText("Novo Salário:");
        jPanel3.add(lb_novoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 20));
        labels.add(lb_novoSalario);
        jPanel3.add(txt_novoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 150, -1));

        lb_novoNomeFantasia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_novoNomeFantasia.setText("Novo Nome Fantasia:");
        jPanel3.add(lb_novoNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));
        labels.add(lb_novoNomeFantasia);
        jPanel3.add(txt_novoNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 180, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 10, 90));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 10, 90));

        jPanelFundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 760, 240));
        panels.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("CPF:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        labels.add(jLabel12);
        jPanel4.add(txt_deleteCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 220, -1));

        bt_deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletar.setText("Deletar");
        bt_deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaFuncionario.this.mouseReleased(evt);
            }
        });
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });
        jPanel4.add(bt_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 400, 30));
        botoes.add(bt_deletar);

        jPanelFundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 420, 240));
        panels.add(jPanel4);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Deletar Funcionário");
        jPanelFundo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));
        labels.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Atualizar Funcionário");
        jPanelFundo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));
        labels.add(jLabel11);

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoItemStateChanged
        if (cb_tipo.getSelectedItem().toString().equalsIgnoreCase(
                "cozinheiro"
        )) {            
            lb_nomeFantasia.setVisible(true);
            txt_nomeFantasia.setVisible(true);
        }
        else {
            lb_nomeFantasia.setVisible(false);
            txt_nomeFantasia.setVisible(false);
        }
            
        
    }//GEN-LAST:event_cb_tipoItemStateChanged

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_ENTER);
    }//GEN-LAST:event_mousePressed

    private void mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseReleased
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO);
    }//GEN-LAST:event_mouseReleased

    private void ckb_atualizarNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_atualizarNomeFantasiaActionPerformed
        lb_novoNomeFantasia.setVisible(ckb_atualizarNomeFantasia.isSelected());
        txt_novoNomeFantasia.setVisible(ckb_atualizarNomeFantasia.isSelected());
    }//GEN-LAST:event_ckb_atualizarNomeFantasiaActionPerformed

    private void ckb_atualizarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_atualizarCPFActionPerformed
        lb_novoCPF.setVisible(ckb_atualizarCPF.isSelected());
        txt_novoCPF.setVisible(ckb_atualizarCPF.isSelected());
    }//GEN-LAST:event_ckb_atualizarCPFActionPerformed

    private void ckb_atualizarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_atualizarNomeActionPerformed
        lb_novoNome.setVisible(ckb_atualizarNome.isSelected());
        txt_novoNome.setVisible(ckb_atualizarNome.isSelected());
    }//GEN-LAST:event_ckb_atualizarNomeActionPerformed

    private void ckb_atualizarDataIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_atualizarDataIngressoActionPerformed
        lb_novaDataIngresso.setVisible(ckb_atualizarDataIngresso.isSelected());
        txt_novaDataIngresso.setVisible(ckb_atualizarDataIngresso.isSelected());
    }//GEN-LAST:event_ckb_atualizarDataIngressoActionPerformed

    private void ckb_atualizarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_atualizarSalarioActionPerformed
        lb_novoSalario.setVisible(ckb_atualizarSalario.isSelected());
        txt_novoSalario.setVisible(ckb_atualizarSalario.isSelected());
    }//GEN-LAST:event_ckb_atualizarSalarioActionPerformed

    private void bt_listarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarTodosActionPerformed
        
        try {
            
            BancoDeDados banco = BancoDeDados.getInstance(
                    usuario,
                      senha,
           nomedb
            );
            
            ArrayList<Funcionario> funcionarios = banco.getFuncionarios();
            mostrarFuncionarios(funcionarios);            
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
        
        
        
    }//GEN-LAST:event_bt_listarTodosActionPerformed

    private void bt_procurarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_procurarCPFActionPerformed
        try {
            
            String cpf = JOptionPane.showInputDialog(
                    this,
                    "Digite o CPF do funcionário:"
            );
            
            if (cpf == null || cpf.equals(""))
                return;
            
            BancoDeDados banco = BancoDeDados.getInstance(
                    usuario,
                    senha,
          nomedb
            );
            
            Funcionario funcionario = banco.getFuncionarioCPF(cpf);
            var funcionarios = new ArrayList<Funcionario>();
            funcionarios.add(funcionario);
            mostrarFuncionarios(funcionarios);
                                    
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_procurarCPFActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        
        try {
            
            String cpf = txt_deleteCPF.getText();
            
            if (cpf.equals(""))
                return;
            
            BancoDeDados banco = BancoDeDados.getInstance(
              usuario,
                senha,
          nomedb
            );
            
            banco.deletarFuncionario(cpf);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Funcionário deletado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
                                    
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        
        try {

            BancoDeDados banco = BancoDeDados.getInstance(
                  usuario,
                    senha,
              nomedb
                );

            String nome = "";
            String cpf = "";
            float salario = 0;
            Date dataIngresso = null;
            String nomeFantasia = "";
            Cargo.tipo cargo = null;
            
            if (txt_nome.getText().equals(""))
                throw new Exception(
                        "Erro: nome é um campo obrigatório"
                );
            
            if (txt_cpf.getText().equals(""))
                throw new Exception(
                        "Erro: cpf é um campo obrigatório"
                );
            
            if (txt_salario.getText().equals(""))
                throw new Exception(
                        "Erro: salario é um campo obrigatório"
                );
            
            if (txt_dataIngresso.getText().equals(""))
                throw new Exception(
                        "Erro: data de ingresso é um campo obrigatório"
                );
            
            cpf = txt_cpf.getText();
            
            if (! Funcionario.eCPFvalido(cpf))
                throw new Exception(
                        "Erro: CPF inválido"
                );
            
            salario = Float.parseFloat(
                    txt_salario.getText()
            );
            
            
            SimpleDateFormat dataFormato = new SimpleDateFormat(
                    "dd/MM/yyyy"
            );
            
            dataIngresso = dataFormato.parse(txt_dataIngresso.getText());
            
            nome = txt_nome.getText();
            
            if (cb_tipo.getSelectedItem().toString().equalsIgnoreCase(
                    "cozinheiro")
            ) {
                cargo = Cargo.tipo.COZINHEIRO;
                nomeFantasia = txt_nomeFantasia.getText();
                
            } else if(cb_tipo.getSelectedItem().toString().equalsIgnoreCase(
                    "degustador")
            ) {
                cargo = Cargo.tipo.DEGUSTADOR;
            } else {
                cargo = Cargo.tipo.EDITOR;
            }
            

            
            banco.inserirFuncionario(
                    cpf,
                    nome,
                    dataIngresso,
                    salario,
                    nomeFantasia,
                    cargo
            );
            
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Funcionário deletado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
        
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );            
        }
        
        
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_listarTodos;
    private javax.swing.JButton bt_procurarCPF;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JCheckBox ckb_atualizarCPF;
    private javax.swing.JCheckBox ckb_atualizarDataIngresso;
    private javax.swing.JCheckBox ckb_atualizarNome;
    private javax.swing.JCheckBox ckb_atualizarNomeFantasia;
    private javax.swing.JCheckBox ckb_atualizarSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_consulta;
    private javax.swing.JLabel lb_nomeFantasia;
    private javax.swing.JLabel lb_novaDataIngresso;
    private javax.swing.JLabel lb_novoCPF;
    private javax.swing.JLabel lb_novoNome;
    private javax.swing.JLabel lb_novoNomeFantasia;
    private javax.swing.JLabel lb_novoSalario;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_cpfFuncionarioAserAtualizado;
    private javax.swing.JTextField txt_dataIngresso;
    private javax.swing.JTextField txt_deleteCPF;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_nomeFantasia;
    private javax.swing.JTextField txt_novaDataIngresso;
    private javax.swing.JTextField txt_novoCPF;
    private javax.swing.JTextField txt_novoNome;
    private javax.swing.JTextField txt_novoNomeFantasia;
    private javax.swing.JTextField txt_novoSalario;
    private javax.swing.JTextField txt_salario;
    // End of variables declaration//GEN-END:variables
}
