/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceGrafica;

import Receita.IngredienteReceita;
import Receita.Receita;
import bancoDeDados.BancoDeDados;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import restaurantes.Restaurante;

/**
 *
 * @author junio
 */
public class TelaReceitaCriar extends javax.swing.JFrame {

    
    ArrayList<JButton> botoes;
    ArrayList<JLabel> labels;
    ArrayList<JPanel> panels;
    String usuario = "postgres";
    String senha = "1Z2ht6b.";
    String nomedb = "CMP1611_Felipe_Valteci_Willian";
    
    ArrayList<IngredienteReceita> ingredientes = null;
    
    public TelaReceitaCriar() {
        botoes = new ArrayList<>();
        labels = new ArrayList<>();
        panels = new ArrayList<>();
        ingredientes = new ArrayList<>();
        initComponents();
        configurarTela();
        configurarCores();
    }
    
    public void mostrarIngredientes() {
        
        DefaultTableModel model = (DefaultTableModel) 
                                   jTable_consulta.getModel();
        
        while (model.getRowCount()> 0)
            model.removeRow(0);
        
        for (IngredienteReceita ingrediente : ingredientes) {
                model.addRow(new Object[]{
                    ingrediente.getCodigoIngrediente(),
                    ingrediente.getQuantidade(),
                    ingrediente.getMedida()
                });
        }
    }
    
    private void configurarCores() {
        jPanelFundo.setBackground(PaletaCores.FUNDO);
        jPanelTitulo.setBackground(PaletaCores.FUNDO);
        jTable_consulta.setBackground(PaletaCores.FUNDO);
        
        for (var label : labels)
            label.setForeground(PaletaCores.TEXTO_FONTE);
        
        for (var panel : panels)
            panel.setBackground(PaletaCores.PANEL_FUNDO);
        
        for (var botao : botoes)
            botao.setBackground(PaletaCores.BOTAO);
    }
    
    private void configurarTela() {
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_nomeReceita = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nomeCozinheiro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dataCriacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cpfCozinheiro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_codigoCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_codigoReceita = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_codigoIngrediente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_medida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_consulta = new javax.swing.JTable();
        bt_acionarIngrediente = new javax.swing.JButton();
        bt_removerTudo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bt_cirarReceita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR RECEITAS");
        jPanelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 550, 30));

        jPanelFundo.add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 90));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt_nomeReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome da Receita:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome do Cozinheiro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));
        jPanel1.add(txt_nomeCozinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Data de Criação:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, -1));

        txt_dataCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataCriacaoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dataCriacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("CPF do Cozinheiro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, -1));

        txt_cpfCozinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfCozinheiroActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cpfCozinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Código da categoria");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, -1));

        txt_codigoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_codigoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Código Receita:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, -1));
        jPanel1.add(txt_codigoReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 180, -1));

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 440, 310));
        panels.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txt_codigoIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Código ingrediente");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("quantidade:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));
        jPanel2.add(txt_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Medida");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        txt_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_medidaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_medida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, -1));

        jTable_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Ingrediente", "Quantidade", "Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_consulta.setToolTipText("");
        jScrollPane1.setViewportView(jTable_consulta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 510, 130));

        bt_acionarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_acionarIngrediente.setText("Adicionar Ingrediente à Receita");
        bt_acionarIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaReceitaCriar.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaReceitaCriar.this.mouseReleased(evt);
            }
        });
        bt_acionarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acionarIngredienteActionPerformed(evt);
            }
        });
        jPanel2.add(bt_acionarIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 510, 30));
        botoes.add(bt_acionarIngrediente);

        bt_removerTudo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_removerTudo.setText("Remover tudo");
        bt_removerTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaReceitaCriar.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaReceitaCriar.this.mouseReleased(evt);
            }
        });
        bt_removerTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerTudoActionPerformed(evt);
            }
        });
        jPanel2.add(bt_removerTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));
        botoes.add(bt_removerTudo);

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 550, 360));
        panels.add(jPanel2);

        jLabel12.setText("Ingredientes");
        jPanelFundo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        bt_cirarReceita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cirarReceita.setText("Criar Receita");
        bt_cirarReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaReceitaCriar.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaReceitaCriar.this.mouseReleased(evt);
            }
        });
        bt_cirarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cirarReceitaActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_cirarReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 150, 40));
        botoes.add(bt_cirarReceita);

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoCategoriaActionPerformed

    private void txt_dataCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataCriacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataCriacaoActionPerformed

    private void txt_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_medidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_medidaActionPerformed

    private void bt_cirarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cirarReceitaActionPerformed
        
        try {
            
            int codigoReceita = Integer.parseInt(
                    txt_codigoReceita.getText()
            );
            
            String nomeReceita = txt_nomeReceita.getText();
            String nomeCozinheiro = txt_nomeCozinheiro.getText();
            Date dataCriacao = null;
            
            SimpleDateFormat dataFormato = new SimpleDateFormat(
                    "dd/MM/yyyy"
            );
            
            dataCriacao = dataFormato.parse(txt_dataCriacao.getText());
            
            String cpfCozinheiro = txt_cpfCozinheiro.getText();
            
            int codigoCategoria = Integer.parseInt(
                    txt_codigoCategoria.getText()
            );
            
            
            Receita receita = new Receita(
                    codigoReceita,
                    nomeReceita,
                    dataCriacao,
                    nomeCozinheiro,
                    cpfCozinheiro,
                    codigoCategoria
            );
            
            BancoDeDados banco = BancoDeDados.getInstance(
                    usuario,
                    senha,
                    nomedb
            );
            
            banco.inserirReceita(receita, ingredientes);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Receita Cadastrada com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_cirarReceitaActionPerformed

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_ENTER);
    }//GEN-LAST:event_mousePressed

    private void mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseReleased
        
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO);
    }//GEN-LAST:event_mouseReleased

    private void txt_cpfCozinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfCozinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfCozinheiroActionPerformed

    private void bt_acionarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acionarIngredienteActionPerformed
        
        try {
            
            int codigoIngrediente = Integer.parseInt(
                    txt_codigoIngrediente.getText()
            );
            
            int quantidade = Integer.parseInt(
                    txt_quantidade.getText()
            );
            
            String medida = txt_medida.getText();
            
            IngredienteReceita ingrediente = new IngredienteReceita(
                    codigoIngrediente,
                    quantidade,
                    medida
            );
            
            ingredientes.add(ingrediente);
            
            mostrarIngredientes();
            
            
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
        
    }//GEN-LAST:event_bt_acionarIngredienteActionPerformed

    private void bt_removerTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerTudoActionPerformed
        
        ingredientes.clear();
        mostrarIngredientes();
    }//GEN-LAST:event_bt_removerTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaCriar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaCriar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaCriar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaCriar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReceitaCriar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_acionarIngrediente;
    private javax.swing.JButton bt_cirarReceita;
    private javax.swing.JButton bt_removerTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_consulta;
    private javax.swing.JTextField txt_codigoCategoria;
    private javax.swing.JTextField txt_codigoIngrediente;
    private javax.swing.JTextField txt_codigoReceita;
    private javax.swing.JTextField txt_cpfCozinheiro;
    private javax.swing.JTextField txt_dataCriacao;
    private javax.swing.JTextField txt_medida;
    private javax.swing.JTextField txt_nomeCozinheiro;
    private javax.swing.JTextField txt_nomeReceita;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
