/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceGrafica;

import bancoDeDados.BancoDeDados;
import categoria.Categoria;
import funcionarios.Cargo;
import funcionarios.Cozinheiro;
import funcionarios.Degustador;
import funcionarios.Funcionario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import restaurantes.Restaurante;

/**
 *
 * @author junio
 */
public class TelaCategoria extends javax.swing.JFrame {

    ArrayList<JButton> botoes;
    ArrayList<JLabel> labels;
    ArrayList<JPanel> panels;
    String usuario = "postgres";
    String senha = "1Z2ht6b.";
    String nomedb = "CMP1611_Felipe_Valteci_Willian";
    
    public TelaCategoria() {
        botoes = new ArrayList<>();
        labels = new ArrayList<>();
        panels = new ArrayList<>();
        initComponents();
        configurarTela();
        configurarCores();
    }
    
    private void mostrarCategoria(ArrayList<Categoria> categorias) {
        
        DefaultTableModel model = (DefaultTableModel) 
                                   jTable_consulta.getModel();
        
        while (model.getRowCount()> 0)
            model.removeRow(0);
        
        for (Categoria categoria : categorias) {
            model.addRow(new Object[]{
                categoria.getCodigo(),
                categoria.getDescricao(),
            });
            }
        }
    
    
    private void configurarCores() {
        jPanelFundo.setBackground(PaletaCores.FUNDO);
        jPanelTitulo.setBackground(PaletaCores.FUNDO);
        jTable_consulta.setBackground(PaletaCores.FUNDO);
        
        for (var label : labels)
            label.setForeground(PaletaCores.TEXTO_FONTE);
        
        for (var panel : panels)
            panel.setBackground(PaletaCores.PANEL_FUNDO);
        
        for (var botao : botoes)
            botao.setBackground(PaletaCores.BOTAO);
    }
    
    private void configurarTela() {
        this.setLocationRelativeTo(null);                                
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_cadastrarDescricao = new javax.swing.JTextField();
        bt_cadastrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_novaDescricao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_atualizarCodigo = new javax.swing.JTextField();
        bt_artualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txt_deletarCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bt_deletar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_consulta = new javax.swing.JTable();
        bt_listarTodos = new javax.swing.JButton();
        bt_procurarCodigo = new javax.swing.JButton();
        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Descrição:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));
        jPanel2.add(txt_cadastrarDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, -1));

        bt_cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mouseReleased(evt);
            }
        });
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, -1));
        botoes.add(bt_cadastrar);

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 600, 70));
        panels.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Código:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));
        jPanel3.add(txt_novaDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nova Descrição: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));
        jPanel3.add(txt_atualizarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, -1));

        bt_artualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_artualizar.setText("Atualizar");
        bt_artualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mouseReleased(evt);
            }
        });
        bt_artualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_artualizarActionPerformed(evt);
            }
        });
        jPanel3.add(bt_artualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, -1));
        botoes.add(bt_artualizar);

        jPanelFundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 600, 100));
        panels.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(txt_deletarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Código:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, -1));

        bt_deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletar.setText("Deletar");
        bt_deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mouseReleased(evt);
            }
        });
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });
        jPanel4.add(bt_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 140, -1));
        botoes.add(bt_deletar);

        jPanelFundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 590, 90));
        panels.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_consulta);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 420, 190));

        bt_listarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_listarTodos.setText("Listar Todos");
        bt_listarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mouseReleased(evt);
            }
        });
        bt_listarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarTodosActionPerformed(evt);
            }
        });
        jPanel5.add(bt_listarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, -1));
        botoes.add(bt_listarTodos);

        bt_procurarCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_procurarCodigo.setText("Procurar por Código");
        bt_procurarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaCategoria.this.mouseReleased(evt);
            }
        });
        bt_procurarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_procurarCodigoActionPerformed(evt);
            }
        });
        jPanel5.add(bt_procurarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, -1));
        botoes.add(bt_procurarCodigo);

        jPanelFundo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 450, 270));
        panels.add(jPanel5);

        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATEGORIA");
        jPanelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 280, -1));

        jPanelFundo.add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Deletar");
        jPanelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Listar Categorias");
        jPanelFundo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Atualizar");
        jPanelFundo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cadastrar");
        jPanelFundo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void bt_listarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarTodosActionPerformed
        
        try {

            BancoDeDados banco = BancoDeDados.getInstance(
                  usuario,
                    senha,
              nomedb
                );

            ArrayList<Categoria> categorias = banco.getCategorias();
            mostrarCategoria(categorias);

        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_listarTodosActionPerformed

    private void bt_artualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_artualizarActionPerformed
                
        try {
            
            int codigo = Integer.parseInt(txt_atualizarCodigo.getText());
            String novaDescricao = txt_novaDescricao.getText();
            
            BancoDeDados banco = BancoDeDados.getInstance(
                    usuario,
                    senha,
                    nomedb
            );
            
            banco.getCategoriaCodigo(codigo);
            banco.atualizarCategoria(codigo, novaDescricao);
            
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Restaurante atualizado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_artualizarActionPerformed

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_ENTER);
    }//GEN-LAST:event_mousePressed

    private void mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseReleased
        
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO);
    }//GEN-LAST:event_mouseReleased

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        
        try {
            String descricao = txt_cadastrarDescricao.getText();
            
            BancoDeDados banco = BancoDeDados.getInstance(
                    usuario,
                    senha,
                    nomedb
            );
            
            banco.inserirCategoria(descricao);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Categoria cadastrada com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_procurarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_procurarCodigoActionPerformed
        try {
            
            String codigo_str = JOptionPane.showInputDialog(
                    this,
                    "Digite o código da categoria:"
            );
            
            if (codigo_str == null || codigo_str.equals(""))
                return;
            
            if (! codigo_str.matches("\\d+"))
                throw new Exception("Erro: código inválido");
            
            int codigo = Integer.parseInt(codigo_str);
            
            BancoDeDados banco = BancoDeDados.getInstance(
                    usuario,
                    senha,
          nomedb
            );
            
            Categoria categoria = banco.getCategoriaCodigo(codigo);
            var categorias = new ArrayList<Categoria>();
            categorias.add(categoria);
            mostrarCategoria(categorias);
                                    
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_procurarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_artualizar;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_listarTodos;
    private javax.swing.JButton bt_procurarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_consulta;
    private javax.swing.JTextField txt_atualizarCodigo;
    private javax.swing.JTextField txt_cadastrarDescricao;
    private javax.swing.JTextField txt_deletarCodigo;
    private javax.swing.JTextField txt_novaDescricao;
    // End of variables declaration//GEN-END:variables
}
