/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceGrafica;

import bancoDeDados.BancoDeDados;
import ingredientes.Ingrediente;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import restaurantes.Restaurante;

/**
 *
 * @author junio
 */
public class TelaIngredientes extends javax.swing.JFrame {

    ArrayList<JButton> botoes;
    ArrayList<JLabel> labels;
    ArrayList<JPanel> panels;
    
    public TelaIngredientes() {
        
        botoes = new ArrayList<>();
        labels = new ArrayList<>();
        panels = new ArrayList<>();
        
        initComponents();
        configurarTela();
        configurarCores();
    }
    
    public void mostrarIngredientes(ArrayList<Ingrediente> ingredientes) {
        
        DefaultTableModel model = (DefaultTableModel) 
                                   jTable_consulta.getModel();
        
        while (model.getRowCount()> 0)
            model.removeRow(0);
        
        for (Ingrediente ingrediente : ingredientes) {
                model.addRow(new Object[]{
                    ingrediente.getCodigo(),
                    ingrediente.getNome()
                });
        }
}
    
    private void configurarTela() {
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    private void configurarCores() {
        jPanelFundo.setBackground(PaletaCores.FUNDO);
        jPanelTitulo.setBackground(PaletaCores.FUNDO);
        jTable_consulta.setBackground(PaletaCores.FUNDO);
        
        for (var label : labels)
            label.setForeground(PaletaCores.TEXTO_FONTE);
        
        for (var panel : panels)
            panel.setBackground(PaletaCores.PANEL_FUNDO);
        
        for (var botao : botoes)
            botao.setBackground(PaletaCores.BOTAO);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_cadastrarNome = new javax.swing.JTextField();
        bt_cadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_deletarCodigo = new javax.swing.JTextField();
        bt_deletar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_atualizarCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_novoNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bt_atualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_consulta = new javax.swing.JTable();
        bt_procurarCodigo = new javax.swing.JButton();
        bt_listarTodos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGREDIENTES");
        jPanelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 380, -1));

        jPanelFundo.add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nome: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));
        jPanel1.add(txt_cadastrarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 200, -1));

        bt_cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mouseReleased(evt);
            }
        });
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 30));
        botoes.add(bt_cadastrar);

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 360, 100));
        panels.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Código: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));
        jPanel2.add(txt_deletarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, -1));

        bt_deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletar.setText("Deletar");
        bt_deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mouseReleased(evt);
            }
        });
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 30));
        botoes.add(bt_deletar);

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 360, 110));
        panels.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txt_atualizarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Código do Ingrediente:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));
        jPanel3.add(txt_novoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Novo Nome:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        bt_atualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_atualizar.setText("Atualizar");
        bt_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mouseReleased(evt);
            }
        });
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });
        jPanel3.add(bt_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, 30));
        botoes.add(bt_atualizar);

        jPanelFundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 360, 150));
        panels.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(PaletaCores.PANEL_BORDA, 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_consulta);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 370, 210));

        bt_procurarCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_procurarCodigo.setText("Procurar por Código");
        bt_procurarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mouseReleased(evt);
            }
        });
        bt_procurarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_procurarCodigoActionPerformed(evt);
            }
        });
        jPanel4.add(bt_procurarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 170, 30));
        botoes.add(bt_procurarCodigo);

        bt_listarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_listarTodos.setText("Listar Todos");
        bt_listarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaIngredientes.this.mouseReleased(evt);
            }
        });
        bt_listarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarTodosActionPerformed(evt);
            }
        });
        jPanel4.add(bt_listarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 30));
        botoes.add(bt_listarTodos);

        jPanelFundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 420, 330));
        panels.add(jPanel4);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Cadastrar Ingredientes");
        jPanelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Deletar Ingrediente");
        jPanelFundo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Atualizar Ingrediente");
        jPanelFundo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Listar Ingredientes");
        jPanelFundo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_ENTER);
    }//GEN-LAST:event_mousePressed

    private void mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseReleased
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO);
    }//GEN-LAST:event_mouseReleased

    private void bt_listarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarTodosActionPerformed
        
        try { 
            
            BancoDeDados banco = BancoDeDados.getInstance();
            
            ArrayList<Ingrediente> ingredientes = banco.getIngredientes();
            mostrarIngredientes(ingredientes);
            
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_listarTodosActionPerformed

    private void bt_procurarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_procurarCodigoActionPerformed
        
        try {
            
            String codigo_str = JOptionPane.showInputDialog(
                    this,
                    "Digite o código do ingrediente:"
            );
            
            if (codigo_str == null || codigo_str.equals(""))
                return;
            
            if (! codigo_str.matches("\\d+"))
                throw new Exception("Erro: código inválido");
            
            int codigo = Integer.parseInt(codigo_str);
            
            BancoDeDados banco = BancoDeDados.getInstance();
            
            Ingrediente ingrediente = banco.getIngredienteCodigo(codigo);
            var ingredientes = new ArrayList<Ingrediente>();
            ingredientes.add(ingrediente);
            mostrarIngredientes(ingredientes);
                                    
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_procurarCodigoActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        
        try {
            String nome = txt_cadastrarNome.getText();
            
            BancoDeDados banco = BancoDeDados.getInstance();
            
            banco.inserirIngrediente(nome);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Ingrediente Cadastrado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        
        try {
            
            int codigo = Integer.parseInt(txt_deletarCodigo.getText());
            
            BancoDeDados banco = BancoDeDados.getInstance();
            
            
            banco.getIngredienteCodigo(codigo);
            banco.deletarIngrediente(codigo);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Ingrediente deletado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        
        try {
            
            int codigo = Integer.parseInt(txt_atualizarCodigo.getText());
            String novoNome = txt_novoNome.getText();
            
            BancoDeDados banco = BancoDeDados.getInstance();
            
            banco.getIngredienteCodigo(codigo);
            banco.atualizarIngrediente(codigo, novoNome);
            
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Ingrediente atualizado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
        } catch(Exception e) {
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bt_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_listarTodos;
    private javax.swing.JButton bt_procurarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_consulta;
    private javax.swing.JTextField txt_atualizarCodigo;
    private javax.swing.JTextField txt_cadastrarNome;
    private javax.swing.JTextField txt_deletarCodigo;
    private javax.swing.JTextField txt_novoNome;
    // End of variables declaration//GEN-END:variables
}
